name: Rust Unit Tests

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout code
      with:
          working-directory: ./lib/cw-core # Set working directory to ./lib/cw-core

    - uses: actions-rs/toolchain@v1  # Install Rust
      with:
          toolchain: stable

    - name: Fetch action
      id: pl
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "./lib/"
        type: ".toml"

    - name: Cargo Check
      working-directory: ./lib/cw-core/
      run: cargo check --release

    - name: Cargo Build
      working-directory: ./lib/cw-core/
      run: cargo build --release

    - name: Cargo Test
      working-directory: ./lib/cw-core/
      run: cargo test --release util

